//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to expose resx entries as strongly-typed
//     properties so XAML can reference them with {x:Static p:Resources.Key}.
//     Regenerate whenever Resources.resx gains or loses a key.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiOtpManager.Properties
{
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    ///   Strongly-typed accessor for the strings in Resources.resx (and its
    ///   culture-specific variants such as Resources.zh-Hans.resx).
    ///   Strings are resolved through the current UI culture; missing keys in
    ///   a localized file fall back to the entries in Resources.resx.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager used to look up localized strings.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Always)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager(
                        "MultiOtpManager.Properties.Resources",
                        typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current UI culture for all resource lookups performed
        ///   by this class. Set this to a specific CultureInfo before touching
        ///   any property to force a particular language at runtime.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Always)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string App_ExecutableTooltip
        {
            get { return ResourceManager.GetString("App_ExecutableTooltip", resourceCulture); }
        }

        public static string App_HeaderTitle
        {
            get { return ResourceManager.GetString("App_HeaderTitle", resourceCulture); }
        }

        public static string App_Title
        {
            get { return ResourceManager.GetString("App_Title", resourceCulture); }
        }

        public static string Button_Activate
        {
            get { return ResourceManager.GetString("Button_Activate", resourceCulture); }
        }

        public static string Button_Assign
        {
            get { return ResourceManager.GetString("Button_Assign", resourceCulture); }
        }

        public static string Button_BackupConfig
        {
            get { return ResourceManager.GetString("Button_BackupConfig", resourceCulture); }
        }

        public static string Button_Cancel
        {
            get { return ResourceManager.GetString("Button_Cancel", resourceCulture); }
        }

        public static string Button_ClearLog
        {
            get { return ResourceManager.GetString("Button_ClearLog", resourceCulture); }
        }

        public static string Button_Close
        {
            get { return ResourceManager.GetString("Button_Close", resourceCulture); }
        }

        public static string Button_CopyUrl
        {
            get { return ResourceManager.GetString("Button_CopyUrl", resourceCulture); }
        }

        public static string Button_Create
        {
            get { return ResourceManager.GetString("Button_Create", resourceCulture); }
        }

        public static string Button_Deactivate
        {
            get { return ResourceManager.GetString("Button_Deactivate", resourceCulture); }
        }

        public static string Button_Delete
        {
            get { return ResourceManager.GetString("Button_Delete", resourceCulture); }
        }

        public static string Button_DisablePin
        {
            get { return ResourceManager.GetString("Button_DisablePin", resourceCulture); }
        }

        public static string Button_ErrorCodes
        {
            get { return ResourceManager.GetString("Button_ErrorCodes", resourceCulture); }
        }

        public static string Button_LdapCheck
        {
            get { return ResourceManager.GetString("Button_LdapCheck", resourceCulture); }
        }

        public static string Button_LdapSync
        {
            get { return ResourceManager.GetString("Button_LdapSync", resourceCulture); }
        }

        public static string Button_LdapUsersList
        {
            get { return ResourceManager.GetString("Button_LdapUsersList", resourceCulture); }
        }

        public static string Button_Lock
        {
            get { return ResourceManager.GetString("Button_Lock", resourceCulture); }
        }

        public static string Button_PurgeLdapCache
        {
            get { return ResourceManager.GetString("Button_PurgeLdapCache", resourceCulture); }
        }

        public static string Button_PurgeLock
        {
            get { return ResourceManager.GetString("Button_PurgeLock", resourceCulture); }
        }

        public static string Button_QrCode
        {
            get { return ResourceManager.GetString("Button_QrCode", resourceCulture); }
        }

        public static string Button_Refresh
        {
            get { return ResourceManager.GetString("Button_Refresh", resourceCulture); }
        }

        public static string Button_Remove
        {
            get { return ResourceManager.GetString("Button_Remove", resourceCulture); }
        }

        public static string Button_RestoreConfig
        {
            get { return ResourceManager.GetString("Button_RestoreConfig", resourceCulture); }
        }

        public static string Button_Resync
        {
            get { return ResourceManager.GetString("Button_Resync", resourceCulture); }
        }

        public static string Button_Save
        {
            get { return ResourceManager.GetString("Button_Save", resourceCulture); }
        }

        public static string Button_ShowLog
        {
            get { return ResourceManager.GetString("Button_ShowLog", resourceCulture); }
        }

        public static string Button_Unlock
        {
            get { return ResourceManager.GetString("Button_Unlock", resourceCulture); }
        }

        public static string Button_Verify
        {
            get { return ResourceManager.GetString("Button_Verify", resourceCulture); }
        }

        public static string Button_Version
        {
            get { return ResourceManager.GetString("Button_Version", resourceCulture); }
        }

        public static string Check_TwoStepHideOtp
        {
            get { return ResourceManager.GetString("Check_TwoStepHideOtp", resourceCulture); }
        }

        public static string Check_UseVerifySwitch
        {
            get { return ResourceManager.GetString("Check_UseVerifySwitch", resourceCulture); }
        }

        public static string Code_0
        {
            get { return ResourceManager.GetString("Code_0", resourceCulture); }
        }

        public static string Code_11
        {
            get { return ResourceManager.GetString("Code_11", resourceCulture); }
        }

        public static string Code_12
        {
            get { return ResourceManager.GetString("Code_12", resourceCulture); }
        }

        public static string Code_13
        {
            get { return ResourceManager.GetString("Code_13", resourceCulture); }
        }

        public static string Code_14
        {
            get { return ResourceManager.GetString("Code_14", resourceCulture); }
        }

        public static string Code_15
        {
            get { return ResourceManager.GetString("Code_15", resourceCulture); }
        }

        public static string Code_16
        {
            get { return ResourceManager.GetString("Code_16", resourceCulture); }
        }

        public static string Code_17
        {
            get { return ResourceManager.GetString("Code_17", resourceCulture); }
        }

        public static string Code_18
        {
            get { return ResourceManager.GetString("Code_18", resourceCulture); }
        }

        public static string Code_19
        {
            get { return ResourceManager.GetString("Code_19", resourceCulture); }
        }

        public static string Code_20
        {
            get { return ResourceManager.GetString("Code_20", resourceCulture); }
        }

        public static string Code_21
        {
            get { return ResourceManager.GetString("Code_21", resourceCulture); }
        }

        public static string Code_22
        {
            get { return ResourceManager.GetString("Code_22", resourceCulture); }
        }

        public static string Code_23
        {
            get { return ResourceManager.GetString("Code_23", resourceCulture); }
        }

        public static string Code_24
        {
            get { return ResourceManager.GetString("Code_24", resourceCulture); }
        }

        public static string Code_25
        {
            get { return ResourceManager.GetString("Code_25", resourceCulture); }
        }

        public static string Code_26
        {
            get { return ResourceManager.GetString("Code_26", resourceCulture); }
        }

        public static string Code_27
        {
            get { return ResourceManager.GetString("Code_27", resourceCulture); }
        }

        public static string Code_28
        {
            get { return ResourceManager.GetString("Code_28", resourceCulture); }
        }

        public static string Code_29
        {
            get { return ResourceManager.GetString("Code_29", resourceCulture); }
        }

        public static string Code_30
        {
            get { return ResourceManager.GetString("Code_30", resourceCulture); }
        }

        public static string Code_31
        {
            get { return ResourceManager.GetString("Code_31", resourceCulture); }
        }

        public static string Code_32
        {
            get { return ResourceManager.GetString("Code_32", resourceCulture); }
        }

        public static string Code_33
        {
            get { return ResourceManager.GetString("Code_33", resourceCulture); }
        }

        public static string Code_34
        {
            get { return ResourceManager.GetString("Code_34", resourceCulture); }
        }

        public static string Code_35
        {
            get { return ResourceManager.GetString("Code_35", resourceCulture); }
        }

        public static string Code_36
        {
            get { return ResourceManager.GetString("Code_36", resourceCulture); }
        }

        public static string Code_37
        {
            get { return ResourceManager.GetString("Code_37", resourceCulture); }
        }

        public static string Code_38
        {
            get { return ResourceManager.GetString("Code_38", resourceCulture); }
        }

        public static string Code_39
        {
            get { return ResourceManager.GetString("Code_39", resourceCulture); }
        }

        public static string Code_40
        {
            get { return ResourceManager.GetString("Code_40", resourceCulture); }
        }

        public static string Code_41
        {
            get { return ResourceManager.GetString("Code_41", resourceCulture); }
        }

        public static string Code_42
        {
            get { return ResourceManager.GetString("Code_42", resourceCulture); }
        }

        public static string Code_43
        {
            get { return ResourceManager.GetString("Code_43", resourceCulture); }
        }

        public static string Code_58
        {
            get { return ResourceManager.GetString("Code_58", resourceCulture); }
        }

        public static string Code_59
        {
            get { return ResourceManager.GetString("Code_59", resourceCulture); }
        }

        public static string Code_60
        {
            get { return ResourceManager.GetString("Code_60", resourceCulture); }
        }

        public static string Code_61
        {
            get { return ResourceManager.GetString("Code_61", resourceCulture); }
        }

        public static string Code_62
        {
            get { return ResourceManager.GetString("Code_62", resourceCulture); }
        }

        public static string Code_63
        {
            get { return ResourceManager.GetString("Code_63", resourceCulture); }
        }

        public static string Code_64
        {
            get { return ResourceManager.GetString("Code_64", resourceCulture); }
        }

        public static string Code_65
        {
            get { return ResourceManager.GetString("Code_65", resourceCulture); }
        }

        public static string Code_66
        {
            get { return ResourceManager.GetString("Code_66", resourceCulture); }
        }

        public static string Code_67
        {
            get { return ResourceManager.GetString("Code_67", resourceCulture); }
        }

        public static string Code_68
        {
            get { return ResourceManager.GetString("Code_68", resourceCulture); }
        }

        public static string Code_69
        {
            get { return ResourceManager.GetString("Code_69", resourceCulture); }
        }

        public static string Code_70
        {
            get { return ResourceManager.GetString("Code_70", resourceCulture); }
        }

        public static string Code_71
        {
            get { return ResourceManager.GetString("Code_71", resourceCulture); }
        }

        public static string Code_72
        {
            get { return ResourceManager.GetString("Code_72", resourceCulture); }
        }

        public static string Code_73
        {
            get { return ResourceManager.GetString("Code_73", resourceCulture); }
        }

        public static string Code_79
        {
            get { return ResourceManager.GetString("Code_79", resourceCulture); }
        }

        public static string Code_80
        {
            get { return ResourceManager.GetString("Code_80", resourceCulture); }
        }

        public static string Code_81
        {
            get { return ResourceManager.GetString("Code_81", resourceCulture); }
        }

        public static string Code_82
        {
            get { return ResourceManager.GetString("Code_82", resourceCulture); }
        }

        public static string Code_88
        {
            get { return ResourceManager.GetString("Code_88", resourceCulture); }
        }

        public static string Code_89
        {
            get { return ResourceManager.GetString("Code_89", resourceCulture); }
        }

        public static string Code_90
        {
            get { return ResourceManager.GetString("Code_90", resourceCulture); }
        }

        public static string Code_91
        {
            get { return ResourceManager.GetString("Code_91", resourceCulture); }
        }

        public static string Code_92
        {
            get { return ResourceManager.GetString("Code_92", resourceCulture); }
        }

        public static string Code_93
        {
            get { return ResourceManager.GetString("Code_93", resourceCulture); }
        }

        public static string Code_94
        {
            get { return ResourceManager.GetString("Code_94", resourceCulture); }
        }

        public static string Code_95
        {
            get { return ResourceManager.GetString("Code_95", resourceCulture); }
        }

        public static string Code_96
        {
            get { return ResourceManager.GetString("Code_96", resourceCulture); }
        }

        public static string Code_97
        {
            get { return ResourceManager.GetString("Code_97", resourceCulture); }
        }

        public static string Code_98
        {
            get { return ResourceManager.GetString("Code_98", resourceCulture); }
        }

        public static string Code_99
        {
            get { return ResourceManager.GetString("Code_99", resourceCulture); }
        }

        public static string Code_Unknown
        {
            get { return ResourceManager.GetString("Code_Unknown", resourceCulture); }
        }

        public static string Dialog_BackupMessage
        {
            get { return ResourceManager.GetString("Dialog_BackupMessage", resourceCulture); }
        }

        public static string Dialog_BackupTitle
        {
            get { return ResourceManager.GetString("Dialog_BackupTitle", resourceCulture); }
        }

        public static string Dialog_ClearLogMessage
        {
            get { return ResourceManager.GetString("Dialog_ClearLogMessage", resourceCulture); }
        }

        public static string Dialog_ClearLogTitle
        {
            get { return ResourceManager.GetString("Dialog_ClearLogTitle", resourceCulture); }
        }

        public static string Dialog_DeleteTokenMessage
        {
            get { return ResourceManager.GetString("Dialog_DeleteTokenMessage", resourceCulture); }
        }

        public static string Dialog_DeleteTokenTitle
        {
            get { return ResourceManager.GetString("Dialog_DeleteTokenTitle", resourceCulture); }
        }

        public static string Dialog_DeleteUserMessage
        {
            get { return ResourceManager.GetString("Dialog_DeleteUserMessage", resourceCulture); }
        }

        public static string Dialog_DeleteUserTitle
        {
            get { return ResourceManager.GetString("Dialog_DeleteUserTitle", resourceCulture); }
        }

        public static string Dialog_LanguageChangeTitle
        {
            get { return ResourceManager.GetString("Dialog_LanguageChangeTitle", resourceCulture); }
        }

        public static string Dialog_LdapSyncMessage
        {
            get { return ResourceManager.GetString("Dialog_LdapSyncMessage", resourceCulture); }
        }

        public static string Dialog_LdapSyncTitle
        {
            get { return ResourceManager.GetString("Dialog_LdapSyncTitle", resourceCulture); }
        }

        public static string Dialog_PurgeLdapCacheMessage
        {
            get { return ResourceManager.GetString("Dialog_PurgeLdapCacheMessage", resourceCulture); }
        }

        public static string Dialog_PurgeLdapCacheTitle
        {
            get { return ResourceManager.GetString("Dialog_PurgeLdapCacheTitle", resourceCulture); }
        }

        public static string Dialog_PurgeLocksMessage
        {
            get { return ResourceManager.GetString("Dialog_PurgeLocksMessage", resourceCulture); }
        }

        public static string Dialog_PurgeLocksTitle
        {
            get { return ResourceManager.GetString("Dialog_PurgeLocksTitle", resourceCulture); }
        }

        public static string Dialog_QrCodeErrorFallback
        {
            get { return ResourceManager.GetString("Dialog_QrCodeErrorFallback", resourceCulture); }
        }

        public static string Dialog_QrCodeHint
        {
            get { return ResourceManager.GetString("Dialog_QrCodeHint", resourceCulture); }
        }

        public static string Dialog_QrCodeTitle
        {
            get { return ResourceManager.GetString("Dialog_QrCodeTitle", resourceCulture); }
        }

        public static string Dialog_RestoreMessage
        {
            get { return ResourceManager.GetString("Dialog_RestoreMessage", resourceCulture); }
        }

        public static string Dialog_RestoreTitle
        {
            get { return ResourceManager.GetString("Dialog_RestoreTitle", resourceCulture); }
        }

        public static string Dialog_ResyncTokenMessage
        {
            get { return ResourceManager.GetString("Dialog_ResyncTokenMessage", resourceCulture); }
        }

        public static string Dialog_ResyncTokenTitle
        {
            get { return ResourceManager.GetString("Dialog_ResyncTokenTitle", resourceCulture); }
        }

        public static string Dialog_SettingsNotSavedTitle
        {
            get { return ResourceManager.GetString("Dialog_SettingsNotSavedTitle", resourceCulture); }
        }

        public static string Dialog_UserNotFoundMessage
        {
            get { return ResourceManager.GetString("Dialog_UserNotFoundMessage", resourceCulture); }
        }

        public static string Dialog_UserNotFoundTitle
        {
            get { return ResourceManager.GetString("Dialog_UserNotFoundTitle", resourceCulture); }
        }

        public static string Label_Created
        {
            get { return ResourceManager.GetString("Label_Created", resourceCulture); }
        }

        public static string Label_Description
        {
            get { return ResourceManager.GetString("Label_Description", resourceCulture); }
        }

        public static string Label_Language
        {
            get { return ResourceManager.GetString("Label_Language", resourceCulture); }
        }

        public static string Label_LogonProviders
        {
            get { return ResourceManager.GetString("Label_LogonProviders", resourceCulture); }
        }

        public static string Label_LogonScope
        {
            get { return ResourceManager.GetString("Label_LogonScope", resourceCulture); }
        }

        public static string Label_NewUser
        {
            get { return ResourceManager.GetString("Label_NewUser", resourceCulture); }
        }

        public static string Label_Otp
        {
            get { return ResourceManager.GetString("Label_Otp", resourceCulture); }
        }

        public static string Label_OtpDigits
        {
            get { return ResourceManager.GetString("Label_OtpDigits", resourceCulture); }
        }

        public static string Label_Password
        {
            get { return ResourceManager.GetString("Label_Password", resourceCulture); }
        }

        public static string Label_ProvisioningUrl
        {
            get { return ResourceManager.GetString("Label_ProvisioningUrl", resourceCulture); }
        }

        public static string Label_Status
        {
            get { return ResourceManager.GetString("Label_Status", resourceCulture); }
        }

        public static string Label_TimeoutSeconds
        {
            get { return ResourceManager.GetString("Label_TimeoutSeconds", resourceCulture); }
        }

        public static string Label_TokenId
        {
            get { return ResourceManager.GetString("Label_TokenId", resourceCulture); }
        }

        public static string Label_TokenType
        {
            get { return ResourceManager.GetString("Label_TokenType", resourceCulture); }
        }

        public static string Label_UnlockProviders
        {
            get { return ResourceManager.GetString("Label_UnlockProviders", resourceCulture); }
        }

        public static string Label_UnlockScope
        {
            get { return ResourceManager.GetString("Label_UnlockScope", resourceCulture); }
        }

        public static string Label_Username
        {
            get { return ResourceManager.GetString("Label_Username", resourceCulture); }
        }

        public static string Language_ChineseSimplified
        {
            get { return ResourceManager.GetString("Language_ChineseSimplified", resourceCulture); }
        }

        public static string Language_English
        {
            get { return ResourceManager.GetString("Language_English", resourceCulture); }
        }

        public static string Language_SystemDefault
        {
            get { return ResourceManager.GetString("Language_SystemDefault", resourceCulture); }
        }

        public static string Message_AuthenticationAccepted
        {
            get { return ResourceManager.GetString("Message_AuthenticationAccepted", resourceCulture); }
        }

        public static string Message_AuthenticationRefused
        {
            get { return ResourceManager.GetString("Message_AuthenticationRefused", resourceCulture); }
        }

        public static string Message_AuthenticationRefusedExitCode
        {
            get { return ResourceManager.GetString("Message_AuthenticationRefusedExitCode", resourceCulture); }
        }

        public static string Message_BackupCreated
        {
            get { return ResourceManager.GetString("Message_BackupCreated", resourceCulture); }
        }

        public static string Message_CommandFailed
        {
            get { return ResourceManager.GetString("Message_CommandFailed", resourceCulture); }
        }

        public static string Message_ConfigurationRestored
        {
            get { return ResourceManager.GetString("Message_ConfigurationRestored", resourceCulture); }
        }

        public static string Message_DeleteFailed
        {
            get { return ResourceManager.GetString("Message_DeleteFailed", resourceCulture); }
        }

        public static string Message_DetailsLoaded
        {
            get { return ResourceManager.GetString("Message_DetailsLoaded", resourceCulture); }
        }

        public static string Message_DisablePinFailed
        {
            get { return ResourceManager.GetString("Message_DisablePinFailed", resourceCulture); }
        }

        public static string Message_EnterBackupPassword
        {
            get { return ResourceManager.GetString("Message_EnterBackupPassword", resourceCulture); }
        }

        public static string Message_EnterRestorePassword
        {
            get { return ResourceManager.GetString("Message_EnterRestorePassword", resourceCulture); }
        }

        public static string Message_EnterTokenIdToDelete
        {
            get { return ResourceManager.GetString("Message_EnterTokenIdToDelete", resourceCulture); }
        }

        public static string Message_EnterUsername
        {
            get { return ResourceManager.GetString("Message_EnterUsername", resourceCulture); }
        }

        public static string Message_ErrorCodesLoaded
        {
            get { return ResourceManager.GetString("Message_ErrorCodesLoaded", resourceCulture); }
        }

        public static string Message_LanguageChangedToSystemDefault
        {
            get { return ResourceManager.GetString("Message_LanguageChangedToSystemDefault", resourceCulture); }
        }

        public static string Message_LanguageRestartRequired
        {
            get { return ResourceManager.GetString("Message_LanguageRestartRequired", resourceCulture); }
        }

        public static string Message_LdapCachePurged
        {
            get { return ResourceManager.GetString("Message_LdapCachePurged", resourceCulture); }
        }

        public static string Message_LdapCheckFinished
        {
            get { return ResourceManager.GetString("Message_LdapCheckFinished", resourceCulture); }
        }

        public static string Message_LdapSyncFinished
        {
            get { return ResourceManager.GetString("Message_LdapSyncFinished", resourceCulture); }
        }

        public static string Message_LdapUserListLoaded
        {
            get { return ResourceManager.GetString("Message_LdapUserListLoaded", resourceCulture); }
        }

        public static string Message_LockFolderPurged
        {
            get { return ResourceManager.GetString("Message_LockFolderPurged", resourceCulture); }
        }

        public static string Message_LogCleared
        {
            get { return ResourceManager.GetString("Message_LogCleared", resourceCulture); }
        }

        public static string Message_LogLoaded
        {
            get { return ResourceManager.GetString("Message_LogLoaded", resourceCulture); }
        }

        public static string Message_MultiotpNotFound
        {
            get { return ResourceManager.GetString("Message_MultiotpNotFound", resourceCulture); }
        }

        public static string Message_NoTokensReturned
        {
            get { return ResourceManager.GetString("Message_NoTokensReturned", resourceCulture); }
        }

        public static string Message_NoUsersReturned
        {
            get { return ResourceManager.GetString("Message_NoUsersReturned", resourceCulture); }
        }

        public static string Message_OperationCanceled
        {
            get { return ResourceManager.GetString("Message_OperationCanceled", resourceCulture); }
        }

        public static string Message_OperationFailedWithType
        {
            get { return ResourceManager.GetString("Message_OperationFailedWithType", resourceCulture); }
        }

        public static string Message_OperationTimedOut
        {
            get { return ResourceManager.GetString("Message_OperationTimedOut", resourceCulture); }
        }

        public static string Message_PrefixPinDisabled
        {
            get { return ResourceManager.GetString("Message_PrefixPinDisabled", resourceCulture); }
        }

        public static string Message_QrCodeShown
        {
            get { return ResourceManager.GetString("Message_QrCodeShown", resourceCulture); }
        }

        public static string Message_ResyncFailed
        {
            get { return ResourceManager.GetString("Message_ResyncFailed", resourceCulture); }
        }

        public static string Message_SelectUserFirst
        {
            get { return ResourceManager.GetString("Message_SelectUserFirst", resourceCulture); }
        }

        public static string Message_SelectUserForQrCode
        {
            get { return ResourceManager.GetString("Message_SelectUserForQrCode", resourceCulture); }
        }

        public static string Message_SelectUserToDelete
        {
            get { return ResourceManager.GetString("Message_SelectUserToDelete", resourceCulture); }
        }

        public static string Message_SelectUserToDisablePin
        {
            get { return ResourceManager.GetString("Message_SelectUserToDisablePin", resourceCulture); }
        }

        public static string Message_SelectUserToResync
        {
            get { return ResourceManager.GetString("Message_SelectUserToResync", resourceCulture); }
        }

        public static string Message_SettingsNotSaved
        {
            get { return ResourceManager.GetString("Message_SettingsNotSaved", resourceCulture); }
        }

        public static string Message_SettingsSaved
        {
            get { return ResourceManager.GetString("Message_SettingsSaved", resourceCulture); }
        }

        public static string Message_TokenAssigned
        {
            get { return ResourceManager.GetString("Message_TokenAssigned", resourceCulture); }
        }

        public static string Message_TokenDeleted
        {
            get { return ResourceManager.GetString("Message_TokenDeleted", resourceCulture); }
        }

        public static string Message_TokenListLoaded
        {
            get { return ResourceManager.GetString("Message_TokenListLoaded", resourceCulture); }
        }

        public static string Message_TokenNoQrCode
        {
            get { return ResourceManager.GetString("Message_TokenNoQrCode", resourceCulture); }
        }

        public static string Message_TokenRemoved
        {
            get { return ResourceManager.GetString("Message_TokenRemoved", resourceCulture); }
        }

        public static string Message_TokenResynchronized
        {
            get { return ResourceManager.GetString("Message_TokenResynchronized", resourceCulture); }
        }

        public static string Message_TokensLoaded
        {
            get { return ResourceManager.GetString("Message_TokensLoaded", resourceCulture); }
        }

        public static string Message_TwoOtpCodesRequired
        {
            get { return ResourceManager.GetString("Message_TwoOtpCodesRequired", resourceCulture); }
        }

        public static string Message_UserActionFailed
        {
            get { return ResourceManager.GetString("Message_UserActionFailed", resourceCulture); }
        }

        public static string Message_UserActionSucceeded
        {
            get { return ResourceManager.GetString("Message_UserActionSucceeded", resourceCulture); }
        }

        public static string Message_UserCreated
        {
            get { return ResourceManager.GetString("Message_UserCreated", resourceCulture); }
        }

        public static string Message_UserCreationCanceled
        {
            get { return ResourceManager.GetString("Message_UserCreationCanceled", resourceCulture); }
        }

        public static string Message_UserCreationFailed
        {
            get { return ResourceManager.GetString("Message_UserCreationFailed", resourceCulture); }
        }

        public static string Message_UserDeleted
        {
            get { return ResourceManager.GetString("Message_UserDeleted", resourceCulture); }
        }

        public static string Message_UserDetailFailed
        {
            get { return ResourceManager.GetString("Message_UserDetailFailed", resourceCulture); }
        }

        public static string Message_UserListFailed
        {
            get { return ResourceManager.GetString("Message_UserListFailed", resourceCulture); }
        }

        public static string Message_UsersLoaded
        {
            get { return ResourceManager.GetString("Message_UsersLoaded", resourceCulture); }
        }

        public static string Message_VersionLoaded
        {
            get { return ResourceManager.GetString("Message_VersionLoaded", resourceCulture); }
        }

        public static string Option_Disabled
        {
            get { return ResourceManager.GetString("Option_Disabled", resourceCulture); }
        }

        public static string Option_LocalAndRemote
        {
            get { return ResourceManager.GetString("Option_LocalAndRemote", resourceCulture); }
        }

        public static string Option_LocalOnly
        {
            get { return ResourceManager.GetString("Option_LocalOnly", resourceCulture); }
        }

        public static string Option_MultiOtpOnly
        {
            get { return ResourceManager.GetString("Option_MultiOtpOnly", resourceCulture); }
        }

        public static string Option_OtherProvidersAllowed
        {
            get { return ResourceManager.GetString("Option_OtherProvidersAllowed", resourceCulture); }
        }

        public static string Option_RemoteDesktopOnly
        {
            get { return ResourceManager.GetString("Option_RemoteDesktopOnly", resourceCulture); }
        }

        public static string Output_ExitCodeWithMessage
        {
            get { return ResourceManager.GetString("Output_ExitCodeWithMessage", resourceCulture); }
        }

        public static string Output_StandardErrorHeader
        {
            get { return ResourceManager.GetString("Output_StandardErrorHeader", resourceCulture); }
        }

        public static string Output_StandardOutputHeader
        {
            get { return ResourceManager.GetString("Output_StandardOutputHeader", resourceCulture); }
        }

        public static string Prompt_FirstOtpCode
        {
            get { return ResourceManager.GetString("Prompt_FirstOtpCode", resourceCulture); }
        }

        public static string Prompt_Ok
        {
            get { return ResourceManager.GetString("Prompt_Ok", resourceCulture); }
        }

        public static string Prompt_SecondOtpCode
        {
            get { return ResourceManager.GetString("Prompt_SecondOtpCode", resourceCulture); }
        }

        public static string Section_AdLdapIntegration
        {
            get { return ResourceManager.GetString("Section_AdLdapIntegration", resourceCulture); }
        }

        public static string Section_AuthenticationFlow
        {
            get { return ResourceManager.GetString("Section_AuthenticationFlow", resourceCulture); }
        }

        public static string Section_AuthenticationTest
        {
            get { return ResourceManager.GetString("Section_AuthenticationTest", resourceCulture); }
        }

        public static string Section_BackupRestore
        {
            get { return ResourceManager.GetString("Section_BackupRestore", resourceCulture); }
        }

        public static string Section_Cleanup
        {
            get { return ResourceManager.GetString("Section_Cleanup", resourceCulture); }
        }

        public static string Section_Details
        {
            get { return ResourceManager.GetString("Section_Details", resourceCulture); }
        }

        public static string Section_LogViewer
        {
            get { return ResourceManager.GetString("Section_LogViewer", resourceCulture); }
        }

        public static string Section_Output
        {
            get { return ResourceManager.GetString("Section_Output", resourceCulture); }
        }

        public static string Section_Result
        {
            get { return ResourceManager.GetString("Section_Result", resourceCulture); }
        }

        public static string Section_TokenList
        {
            get { return ResourceManager.GetString("Section_TokenList", resourceCulture); }
        }

        public static string Section_TokenOperations
        {
            get { return ResourceManager.GetString("Section_TokenOperations", resourceCulture); }
        }

        public static string Section_UserDetails
        {
            get { return ResourceManager.GetString("Section_UserDetails", resourceCulture); }
        }

        public static string Section_Users
        {
            get { return ResourceManager.GetString("Section_Users", resourceCulture); }
        }

        public static string Status_CancelingOperation
        {
            get { return ResourceManager.GetString("Status_CancelingOperation", resourceCulture); }
        }

        public static string Status_Copied
        {
            get { return ResourceManager.GetString("Status_Copied", resourceCulture); }
        }

        public static string Status_CopyFailed
        {
            get { return ResourceManager.GetString("Status_CopyFailed", resourceCulture); }
        }

        public static string Status_NoTestRun
        {
            get { return ResourceManager.GetString("Status_NoTestRun", resourceCulture); }
        }

        public static string Status_OperationInProgress
        {
            get { return ResourceManager.GetString("Status_OperationInProgress", resourceCulture); }
        }

        public static string Status_Ready
        {
            get { return ResourceManager.GetString("Status_Ready", resourceCulture); }
        }

        public static string Tab_AdLdap
        {
            get { return ResourceManager.GetString("Tab_AdLdap", resourceCulture); }
        }

        public static string Tab_Authentication
        {
            get { return ResourceManager.GetString("Tab_Authentication", resourceCulture); }
        }

        public static string Tab_CredentialProvider
        {
            get { return ResourceManager.GetString("Tab_CredentialProvider", resourceCulture); }
        }

        public static string Tab_Logs
        {
            get { return ResourceManager.GetString("Tab_Logs", resourceCulture); }
        }

        public static string Tab_Maintenance
        {
            get { return ResourceManager.GetString("Tab_Maintenance", resourceCulture); }
        }

        public static string Tab_Tokens
        {
            get { return ResourceManager.GetString("Tab_Tokens", resourceCulture); }
        }

        public static string Tab_Users
        {
            get { return ResourceManager.GetString("Tab_Users", resourceCulture); }
        }

    }
}
